services:
  - type: web
    name: ancom-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: ALLOWED_ORIGIN
        value: https://ancom.vercel.app
